### ISSUE TITLE
link on website goes to file not found

### ISSUE THREAD

**Issue by pacav69** [babobski/komodo-bootstrap-snippets#1]
At this website
http://komodoide.com/packages/toolbox/bootstrap-snippet-collection/

Download source link takes user to this website
https://codeload.github.com/babobski/komodo-bootstrap-snippets/zip/official%20release%20bootstrap%20snippets

Found the files at this location
https://github.com/babobski/komodo-bootstrap-snippets

**Comment by babobski** [comment]
Thanks, is working now, also the download counter is working (was always zero)
